import os
from pathlib import Path

import pandas as pd
import pytest

from regression_model import __version__ as model_version
from regression_model.config.core import config
from regression_model.processing.data_manager import load_dataset

PWD = Path.cwd()


# Load kaggle test.csv data
@pytest.fixture
def sample_input_data() -> pd.DataFrame:
    return load_dataset(file_name=config.app_config.test_data_file)


# Save prediction results for comparison later
@pytest.fixture
def persist_results():
    yield
    label = os.environ.get("DIFF_TEST")
    with open(f"{label}_version.txt", "w") as handler:
        handler.write(model_version)


# Load results generated by the notebook in /research-notebook
@pytest.fixture
def research_model_results() -> pd.DataFrame:
    return pd.read_csv(PWD / "differential_tests" / "research_model_test_results.csv")
